tribezero/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

tribezero/main/routes.py
from flask import render_template, request, Blueprint, url_for, redirect
from flask_login import current_user
import requests
from tribezero.models import Post, CompanyAddress, Shop
from tribezero.config import Config
from tribezero import db

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/welcome")
def welcome():
    return render_template('welcome.html', title='Welcome!')


@main.route("/map")
def sellers_map():
    key = Config.GOOGLE_MAPS_API_KEY

    shops = Shop.query.join(CompanyAddress, Shop.id == CompanyAddress.shop_id)\
        .add_columns(Shop.name, CompanyAddress.company_coordinates_lat, CompanyAddress.company_coordinates_lon,\
                     CompanyAddress.shop_id, Shop.id, Shop.shop_categories, Shop.description)\
        .filter(Shop.id == CompanyAddress.shop_id)
    return render_template('map.html', title='Map', key=key, shops=shops)


@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', posts=posts)

tribezero/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from tribezero import db
from tribezero.models import Post
from tribezero.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

tribezero/shops/routes.py
from datetime import datetime
from sqlalchemy import func
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from tribezero import db
from tribezero.users.forms import CreateShopForm
from tribezero.models import Shop, CompanyAddress, Contact
from tribezero.config import Config
import requests


user_shops = Blueprint('shops', __name__)


@user_shops.route("/open_shop", methods=['GET', 'POST'])
@login_required
def open_shop():
    form = CreateShopForm(company_country="IE")

    if current_user.shop:
        flash('Sorry but you already have a shop. Only one per account.', 'warning')
        return redirect(url_for('main.home'))

    if form.validate_on_submit():
        shop = Shop(name=form.shop_name.data,
                    created=datetime.utcnow(),
                    owner=current_user,
                    shop_categories=form.shop_categories.data
                    )

        key = Config.GOOGLE_MAPS_API_KEY
        google_maps_api_url = "https://maps.googleapis.com/maps/api/geocode/json?"
        address = f"address={form.company_street_line1.data},{form.company_street_line2.data},{form.company_city.data}," \
            f"{form.company_region.data},{form.company_zip_code.data},{dict(form.company_country.choices).get(form.company_country.data)}"
        coordinates_response = requests.get(google_maps_api_url + address + "&key=" + key).json()
        response = coordinates_response["results"][0]

        company_address = CompanyAddress(company_name=form.company_name.data,
                                         company_street_line1=form.company_street_line1.data,
                                         company_street_line2=form.company_street_line2.data,
                                         company_city=form.company_city.data,
                                         company_country=form.company_country.data,
                                         company_region=form.company_region.data,
                                         company_zip_code=form.company_zip_code.data,
                                         company_building_number=form.company_building_number.data,
                                         company_apartment_number=form.company_apartment_number.data,
                                         company_coordinates_lat=response["geometry"]["location"]["lat"],
                                         company_coordinates_lon=response["geometry"]["location"]["lng"],
                                         shop=current_user)

        contact = Contact(email=form.email.data,
                          shop=current_user)

        db.session.add(shop)
        db.session.add(company_address)
        db.session.add(contact)
        db.session.commit()

        flash('Your shop has been opened!', 'success')
        return redirect(url_for('main.home'))
    return render_template('open_shop.html', title='Open Shop', form=form)


@user_shops.route("/shop/<string:name>")
def shop(name):
    shop_id = Shop.query.filter(func.lower(Shop.name) == func.lower(name)).first().id
    shop_info = Shop.query.get_or_404(shop_id)
    return render_template('shop.html', title=name, shop_info=shop_info)


@user_shops.route("/shops")
def shops():
    page = request.args.get('page', 1, type=int)
    shops = Shop.query.order_by(Shop.name.asc()).paginate(page=page, per_page=10)
    return render_template('shops.html', title='Shops', shops=shops)


@user_shops.route("/shop_manager")
@login_required
def shop_manager():
    users_shop = Shop.query.filter_by(owner=current_user).first().name
    return render_template('shop_manager.html', title=users_shop, users_shop=users_shop)

tribezero/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from tribezero import db, bcrypt
from tribezero.models import User, Post
from tribezero.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from tribezero.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. Welcome to the tribe!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check the e-mail and password and try again.', 'danger')
    return render_template('login.html', title='Sign In', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An e-mail has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

tribezero/templates/account.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="Post" action="" novalidate enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Your Account</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

tribezero/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <h2>Reduce! Reuse! Shop Local!</h2>
    <br>
    <h3>Featured Shops Near You</h3>
    <p id="your_location"></p>

{% endblock content %}

tribezero/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags for Bootstrap-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% if title %}
        <title>Tribe Zero - {{ title }}</title>
    {% else %}
        <title>Tribe Zero</title>
    {% endif %}
</head>

<body>
    <div id="container">
        <header class="site-header fixed-top" id="header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-mossy">

                <!-- Logo -->
                <a class="navbar-brand" href="{{ url_for('main.home') }}"><img height="50px" src="{{ url_for('static', filename='tribezero_logo.png') }}">Tribe Zero</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Responsive and collapsing navbar -->
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav ml-5">
                        <li class="nav-item">
                            <a id="home" class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="about" class="nav-link" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a id="shops" class="nav-link" href="{{ url_for('shops.shops') }}">Shops</a>
                        </li>
                        <li class="nav-item">
                            <a id="map" class="nav-link" href="{{ url_for('main.sellers_map') }}">Map</a>
                        </li>
                        <li class="nav-item">
                            <a id="blog" class="nav-link" href="{{ url_for('main.blog') }}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a id="swaps" class="nav-link" href="#">Swaps</a>
                        </li>
                        <li class="nav-item">
                            <a id="events" class="nav-link" href="#">Events</a>
                        </li>
                        <li class="nav-item">
                            <a id="sell" class="nav-link" href="{{ url_for('shops.open_shop') }}">Open Shop</a>
                        </li>
                        <li class="nav-item">
                            <a id="forum" class="nav-link" href="#">Forum</a>
                        </li>
                    </ul>
                </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <div class="dropdown">

                        <!-- Avatar -->
                        <img class="rounded-circle profile-avatar dropdown-toggle" data-toggle="dropdown"
                             src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">

                        <!-- Dropdown menu from avatar -->
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-user d-inline col"></i>
                                <div class="col d-inline">View Profile</div>
                            </a>
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-group d-inline col"></i>
                                <div class="col d-inline">Your Tribes</div>
                            </a>
                            {% if current_user.shop %}
                            <a class="dropdown-item d-block" href="{{ url_for('shops.shop_manager') }}">
                                <i class="fa fa-heart d-inline col"></i>
                                <div class="col d-inline">Shop Manager</div>
                            </a>
                            {% endif %}
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-heart d-inline col"></i>
                                <div class="col d-inline">Favorites</div>
                            </a>
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-envelope d-inline col"></i>
                                <div class="col d-inline">Conversations</div>
                            </a>
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-money d-inline col"></i>
                                <div class="col d-inline">Purchases</div>
                            </a>
                            <a class="dropdown-item d-block" href="#">
                                <i class="fa fa-star d-inline col"></i>
                                <div class="col d-inline">Reviews</div>
                            </a>
                            <a class="dropdown-item d-block" href="{{ url_for('users.account') }}">
                                <i class="fa fa-cog d-inline col"></i>
                                <div class="col d-inline">Account Settings</div>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item d-block" href="{{ url_for('users.logout') }}">
                                <i class="fa fa-sign-out d-inline col"></i>
                                <div class="col d-inline">Logout</div>
                            </a>
                        </div>
                    </div>

                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>

            </nav>


        </header>

        <main role="main" class="site-main container-fluid" id="body">
            <div class="row d-flex justify-content-center mx-0">
                <div class="col-md-6">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}

                </div>
            </div>
            <div>
                {% block shops %}{% endblock %}
                {% block map %}{% endblock %}
            </div>
        </main>

        <footer class="page-footer font-small bg-dark" id="footer">
            <div class="container-fluid text-center">
                <div class="row">
                    <div class="col-sm mt-md-o mt-3">
                        <h5 class="text-uppercase text-light">About</h5>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#!">Tribe Zero</a>
                            </li>
                            <li>
                                <a href="#!">Team</a>
                            </li>
                            <li>
                                <a href="#!">Link 3</a>
                            </li>
                            <li>
                                <a href="#!">Link 4</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm mt-md-o mt-3">
                        <h5 class="text-uppercase text-light">Help</h5>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#!">Help Center</a>
                            </li>
                            <li>
                                <a href="#!">Link 2</a>
                            </li>
                            <li>
                                <a href="#!">Link 3</a>
                            </li>
                            <li>
                                <a href="#!">Link 4</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm mt-md-o mt-3">
                        <h5 class="text-uppercase text-light">Sell</h5>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#!">Become a Trader</a>
                            </li>
                            <li>
                                <a href="#!">Link 2</a>
                            </li>
                            <li>
                                <a href="#!">Link 3</a>
                            </li>
                            <li>    
                                <a href="#!">Link 4</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--Google Maps Script-->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ key }}&callback=initMap" async defer></script>
    <script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"></script>
</body>
<script>
    $(document).ready(function() {
        $('li.active').removeClass('active');
        $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
    });

    var x = document.getElementById("your_location")
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            alert("Geolocation is not supported by this browser.");
        }
    }

    function showPosition(position) {
        x.innerHTML = "Latitude: " + position.coords.latitude +
        "<br>Longitude: " + position.coords.longitude;
    }

    getLocation()
</script>
</html>

tribezero/templates/post.html
{% extends "layout.html" %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">
                            Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                                data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}post.html
            </div>
            <h2 class=""article-title>{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

tribezero/templates/shops.html
{% extends "layout.html" %}

{% block shops %}
    <div class="row d-flex justify-content-center flex-wrap">
        {% for shop in shops.items %}
            <article class="media shop-section mx-2">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='shop_pics/' + shop.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-auto" href="{{ url_for('shops.shops', shop_name=shop.name) }}">{{ shop.name }}</a>
                        <small class="text-muted">{{ shop.created.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <h2 class="text-left"><a class="article-title" href="{{ url_for('shops.shop', name=shop.name) }}">{{ shop.owner.username }}</a></h2>
                    <p class="article-content">{{ shop.description }}</p>
                </div>
            </article>
        {% endfor %}
    </div>
    <div class="text-center">
    {% for page_num in shops.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if shops.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('shops.shops', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('shops.shops', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock shops %}

tribezero/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    <div class="text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock content %}